<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HighScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighScoreRepository extends EntityRepository
{

    public function getHighScore($limit = 10)
    {
        return $this->createQueryBuilder('h')
            ->addOrderBy('h.score', 'DESC')
            ->addOrderBy('h.duration', 'ASC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function isInHighScore($score, $duration, $limit = 10)
    {
        if ($score == 0) {
            return false;
        }
        $result = $this->getEntityManager()
            ->createQuery("
                SELECT COUNT(h.id) as result
                FROM AppBundle:HighScore h
                WHERE h.score >= :score
            ")
            ->setParameters([
                'score' => $score,
                //'duration' => $duration
            ])
            ->getOneOrNullResult();

        if (null === $result) {
            return true;
        }

        return $result['result'] < $limit;
    }
}
