<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HighScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighScoreRepository extends EntityRepository
{

    /**
     * return an array of high score order by score and duration
     *
     * @param int $limit
     * @return array
     */
    public function getHighScore($limit = 10)
    {
        return $this->createQueryBuilder('h')
            ->addOrderBy('h.score', 'DESC')
            ->addOrderBy('h.duration', 'ASC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * check if the combination of $score and $duration can be in the high score.
     *
     * @param $score
     * @param $duration
     * @param int $limit
     * @return bool
     */
    public function isInHighScore($score, $duration, $limit = 10)
    {
        if ($score == 0) {
            return false;
        }
        $highScore = $this->findHighScore($score, $limit);

        if (count($highScore) < $limit) {
            return true;
        }

        if (count($highScore) == $limit) {
            $last = array_pop($highScore);

            if ($duration < $last->getDuration() && $score >= $last->getScore()) {
                return true;
            }
        }

        return false;
    }

    private function findHighScore($score)
    {
        $result = $this->getEntityManager()
            ->createQuery("
                SELECT h
                FROM AppBundle:HighScore h
                WHERE h.score >= :score
                ORDER BY h.score DESC, h.duration ASC
            ")
            ->setParameters([
                'score' => $score,
            ])
            ->getResult();

        return $result;
    }
}
