<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HighScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighScoreRepository extends EntityRepository
{

    public function getHighScore($limit = 10)
    {
        return $this->createQueryBuilder('h')
            ->orderBy('h.score', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function isInHighScore($score, $limit = 10)
    {
        $min = $this->getEntityManager()
            ->createQuery("
                SELECT MIN(h.score) AS min_score
                FROM AppBundle:HighScore h
            ")
            ->setMaxResults($limit)
            ->getSingleScalarResult();

        if (null === $min) {
            $min = 0;
        }

        return $score > $min;
    }
}
