<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function getRandomPerson($excludeMovie)
    {
        $dql = <<<EOL
SELECT %s
FROM AppBundle:Person p
JOIN p.movies m
WHERE m.id NOT IN (:exclude)
EOL;

        $count = $this->getEntityManager()
            ->createQuery(sprintf($dql, "COUNT(p.id) as count_person"))
            ->setParameter('exclude', $excludeMovie)
            ->getSingleScalarResult();

        $offset = rand(0, $count-1);

        return $this->getEntityManager()
            ->createQuery(sprintf($dql, "p"))
            ->setParameter('exclude', $excludeMovie)
            ->setMaxResults(1)
            ->setFirstResult($offset)
            ->getOneOrNullResult();
    }
}
